"""
Loader for the bundled Champions Pokédex (assets/data/champions.json) plus a
Showdown-accurate stat calculator. This is the data layer behind the
teambuilder's species picker and editor.

The dataset is generated by tools/gen_pokedex.py from Serebii's Champions dex.
Loading is lazy and cached; if the file is missing the app still runs (the
picker just shows an empty/legacy state).
"""

from __future__ import annotations

import json
import math
from functools import lru_cache

from .paths import resource_path

STAT_KEYS = ["hp", "atk", "def", "spa", "spd", "spe"]
STAT_LABELS = {"hp": "HP", "atk": "Atk", "def": "Def", "spa": "SpA", "spd": "SpD", "spe": "Spe"}

# Pokémon Champions "Stat Point" (SP) system — replaces EVs and IVs.
#   * IVs are gone; every Pokémon is treated as 31 in every stat.
#   * 66 SP total, 32 SP max per stat; each SP = +1 to that stat at Level 50.
# Converting to the Switch game Berichan injects into (which uses EVs): 8 EVs
# give +1 stat at Lv50, so EV = SP*8 (capped at the game's 252 EV ceiling).
SP_MAX_PER_STAT = 32
SP_MAX_TOTAL = 66
CHAMPIONS_LEVEL = 50
PERFECT_IV = 31


def sp_to_ev(sp: int) -> int:
    """Champions SP -> Showdown/Switch EV for the same Lv50 stat."""
    return min(max(0, sp) * 8, 252)


def ev_to_sp(ev: int) -> int:
    """Showdown EV -> nearest Champions SP (for editing imported sets)."""
    return min(round(max(0, ev) / 8), SP_MAX_PER_STAT)

# Nature -> (boosted stat, hindered stat). Neutral natures map to (None, None).
NATURES: dict[str, tuple[str | None, str | None]] = {
    "": (None, None), "Hardy": (None, None), "Docile": (None, None),
    "Serious": (None, None), "Bashful": (None, None), "Quirky": (None, None),
    "Lonely": ("atk", "def"), "Brave": ("atk", "spe"), "Adamant": ("atk", "spa"),
    "Naughty": ("atk", "spd"), "Bold": ("def", "atk"), "Relaxed": ("def", "spe"),
    "Impish": ("def", "spa"), "Lax": ("def", "spd"), "Timid": ("spe", "atk"),
    "Hasty": ("spe", "def"), "Jolly": ("spe", "spa"), "Naive": ("spe", "spd"),
    "Modest": ("spa", "atk"), "Mild": ("spa", "def"), "Quiet": ("spa", "spe"),
    "Rash": ("spa", "spd"), "Calm": ("spd", "atk"), "Gentle": ("spd", "def"),
    "Sassy": ("spd", "spe"), "Careful": ("spd", "spa"),
}


@lru_cache(maxsize=1)
def _data() -> dict:
    path = resource_path("assets", "data", "champions.json")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"species": []}


@lru_cache(maxsize=1)
def _by_name() -> dict[str, dict]:
    index: dict[str, dict] = {}
    for sp in _data().get("species", []):
        index[sp["name"].lower()] = sp
        index[sp["id"].lower()] = sp
    return index


def is_loaded() -> bool:
    return bool(_data().get("species"))


def all_species() -> list[dict]:
    """All legal species, ordered by national dex number."""
    return sorted(_data().get("species", []), key=lambda s: s.get("num", 0))


def search(query: str) -> list[dict]:
    q = query.strip().lower()
    species = all_species()
    if not q:
        return species
    return [s for s in species if q in s["name"].lower()]


def get_species(name: str) -> dict | None:
    return _by_name().get(name.strip().lower())


def calc_stat(stat: str, base: int, iv: int, ev: int, level: int, nature: str) -> int:
    """Compute a real stat value (gen 3+ formula)."""
    level = level or 50
    common = math.floor((2 * base + iv + ev // 4) * level / 100)
    if stat == "hp":
        if base == 1:  # Shedinja-style
            return 1
        return common + level + 10
    plus, minus = NATURES.get(nature, (None, None))
    mod = 1.1 if stat == plus else 0.9 if stat == minus else 1.0
    return math.floor((common + 5) * mod)


def calc_all_stats(
    base_stats: dict[str, int],
    ivs: dict[str, int],
    evs: dict[str, int],
    level: int,
    nature: str,
) -> dict[str, int]:
    return {
        s: calc_stat(s, base_stats.get(s, 0), ivs.get(STAT_LABELS[s], 31),
                     evs.get(STAT_LABELS[s], 0), level, nature)
        for s in STAT_KEYS
    }


def calc_stat_sp(stat: str, base: int, sp: int, level: int, nature: str) -> int:
    """
    Compute a stat the Champions way: perfect IVs, SP added linearly.
    Equivalent to the standard formula with IV=31 and EV=sp*8 at Lv50.
    """
    level = level or CHAMPIONS_LEVEL
    common = math.floor((2 * base + PERFECT_IV) * level / 100)
    if stat == "hp":
        if base == 1:
            return 1
        return common + level + 10 + sp
    plus, minus = NATURES.get(nature, (None, None))
    mod = 1.1 if stat == plus else 0.9 if stat == minus else 1.0
    return math.floor((common + 5 + sp) * mod)


def calc_all_stats_sp(
    base_stats: dict[str, int],
    sp: dict[str, int],
    level: int,
    nature: str,
) -> dict[str, int]:
    """sp keyed by STAT_ORDER labels (HP/Atk/…). Returns dict keyed by STAT_KEYS."""
    return {
        s: calc_stat_sp(s, base_stats.get(s, 0), sp.get(STAT_LABELS[s], 0), level, nature)
        for s in STAT_KEYS
    }


def sprite_path(species_id: str):
    """Filesystem path to a bundled sprite (may not exist)."""
    return resource_path("assets", "sprites", f"{species_id}.png")
