"""
Competitive "meta" usage data: what moves/items/abilities/natures/SP-spreads
people actually run, with usage %, per format (Doubles/Singles).

Loads the bundled assets/data/meta.json (generated by tools/gen_meta.py). A live
"Refresh" can re-pull the latest from the free championsbattledata.com API and
store it as a user-side override in the app data dir, so updates never touch the
read-only bundle (important once packaged as an .exe).
"""

from __future__ import annotations

import json
import re
import urllib.request
from urllib.parse import quote

from .paths import app_data_dir, resource_path

API = "https://championsbattledata.com"
FORMATS = ["Doubles", "Singles"]
_SEASON = "Current"
_HEADERS = {"User-Agent": "Mozilla/5.0 (BerichanCrossTransfer)"}
_SP_FIELDS = [("HP", "hp_points"), ("Atk", "attack_points"), ("Def", "defense_points"),
              ("SpA", "sp_atk_points"), ("SpD", "sp_def_points"), ("Spe", "speed_points")]

_cache: dict | None = None


def _override_file():
    return app_data_dir() / "meta.json"


def _load() -> dict:
    global _cache
    if _cache is None:
        path = _override_file()
        if not path.exists():
            path = resource_path("assets", "data", "meta.json")
        try:
            _cache = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _cache = {"formats": {f: {} for f in FORMATS}, "season": _SEASON}
    return _cache


def is_loaded() -> bool:
    data = _load().get("formats", {})
    return any(data.get(f) for f in FORMATS)


def season() -> str:
    return _load().get("season", _SEASON)


def get(species_id: str, fmt: str) -> dict:
    return _load().get("formats", {}).get(fmt, {}).get(species_id, {})


def recommended(species_id: str, fmt: str) -> dict:
    """Top-usage set for one-click apply: 4 moves, item, ability, nature, spread."""
    d = get(species_id, fmt)
    if not d:
        return {}
    return {
        "moves": [m[0] for m in d.get("moves", [])[:4]],
        "item": d.get("items", [[None]])[0][0] if d.get("items") else "",
        "ability": d.get("abilities", [[None]])[0][0] if d.get("abilities") else "",
        "nature": d.get("natures", [[None]])[0][0] if d.get("natures") else "",
        "spread": d.get("spreads", [[None]])[0][0] if d.get("spreads") else {},
    }


# ----------------------------------------------------------------------
# Live refresh (blocking — call from an executor)
# ----------------------------------------------------------------------

def _to_id(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _parse_rows(rows: list[dict]) -> dict:
    out = {"moves": [], "items": [], "abilities": [], "natures": [], "spreads": []}
    for r in rows:
        cat, pct = r.get("category"), r.get("percentage_value", 0)
        if cat == "move":
            out["moves"].append([r["name"], pct])
        elif cat == "held_item":
            out["items"].append([r["name"], pct])
        elif cat == "ability":
            out["abilities"].append([r["name"], pct])
        elif cat == "stat_alignment":
            out["natures"].append([r["name"], pct, r.get("stat_up", ""), r.get("stat_down", "")])
        elif cat == "stat_points":
            out["spreads"].append([{lab: int(r.get(f) or 0) for lab, f in _SP_FIELDS}, pct])
    return out


def refresh_species(species_id: str, name: str) -> bool:
    """Pull both formats for one species from the API and persist an override."""
    slug = _to_id(name)
    data = _load()
    data.setdefault("formats", {f: {} for f in FORMATS})
    got = False
    for fmt in FORMATS:
        url = f"{API}/api/battle/{fmt}/{quote(slug)}?season={quote(_SEASON)}"
        try:
            req = urllib.request.Request(url, headers=_HEADERS)
            with urllib.request.urlopen(req, timeout=20) as r:
                rows = json.loads(r.read()).get("rows", [])
        except Exception:  # noqa: BLE001
            continue
        parsed = _parse_rows(rows)
        if any(parsed.values()):
            data["formats"].setdefault(fmt, {})[species_id] = parsed
            got = True
    if got:
        try:
            _override_file().write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
        except OSError:
            pass
    return got
