"""
Loader for the bundled Champions Pokédex (assets/data/champions.json) plus a
Showdown-accurate stat calculator. This is the data layer behind the
teambuilder's species picker and editor.

The dataset is generated by tools/gen_pokedex.py from Serebii's Champions dex.
Loading is lazy and cached; if the file is missing the app still runs (the
picker just shows an empty/legacy state).
"""

from __future__ import annotations

import json
import math
from functools import lru_cache

from .paths import resource_path

STAT_KEYS = ["hp", "atk", "def", "spa", "spd", "spe"]
STAT_LABELS = {"hp": "HP", "atk": "Atk", "def": "Def", "spa": "SpA", "spd": "SpD", "spe": "Spe"}

# Pokémon Champions "Stat Point" (SP) system — replaces EVs and IVs.
#   * IVs are gone; every Pokémon is treated as 31 in every stat.
#   * 66 SP total, 32 SP max per stat; each SP = +1 to that stat at Level 50.
# Converting to the Switch game Berichan injects into (which uses EVs): 8 EVs
# give +1 stat at Lv50, so EV = SP*8 (capped at the game's 252 EV ceiling).
SP_MAX_PER_STAT = 32
SP_MAX_TOTAL = 66
CHAMPIONS_LEVEL = 50
PERFECT_IV = 31


def sp_to_ev(sp: int) -> int:
    """Champions SP -> Showdown/Switch EV for the same Lv50 stat."""
    return min(max(0, sp) * 8, 252)


def ev_to_sp(ev: int) -> int:
    """Showdown EV -> nearest Champions SP (for editing imported sets)."""
    return min(round(max(0, ev) / 8), SP_MAX_PER_STAT)


# Mainline games (Scarlet/Violet, SwSh, …) cap EVs at 510 total / 252 per stat.
# Champions allows 66 SP (~528 EV-equivalent), so a full SP spread can exceed the
# mainline total. We must emit a LEGAL spread or the trade fails to legalize.
MAINLINE_EV_TOTAL = 510


def sp_spread_to_evs(sp: dict[str, int]) -> dict[str, int]:
    """
    Convert a Champions SP spread (keyed by STAT_ORDER labels) into legal
    mainline EVs: each stat capped at 252, and the TOTAL capped at 510 by
    trimming the least-invested stats first (so maxed stats stay exact).
    """
    ev = {label: sp_to_ev(sp.get(label, 0)) for label in STAT_LABELS.values()}
    excess = sum(ev.values()) - MAINLINE_EV_TOTAL
    if excess > 0:
        for label in sorted(ev, key=lambda l: ev[l]):  # smallest first
            if excess <= 0:
                break
            take = min(ev[label], excess)
            ev[label] -= take
            excess -= take
    return ev

# Nature -> (boosted stat, hindered stat). Neutral natures map to (None, None).
NATURES: dict[str, tuple[str | None, str | None]] = {
    "": (None, None), "Hardy": (None, None), "Docile": (None, None),
    "Serious": (None, None), "Bashful": (None, None), "Quirky": (None, None),
    "Lonely": ("atk", "def"), "Brave": ("atk", "spe"), "Adamant": ("atk", "spa"),
    "Naughty": ("atk", "spd"), "Bold": ("def", "atk"), "Relaxed": ("def", "spe"),
    "Impish": ("def", "spa"), "Lax": ("def", "spd"), "Timid": ("spe", "atk"),
    "Hasty": ("spe", "def"), "Jolly": ("spe", "spa"), "Naive": ("spe", "spd"),
    "Modest": ("spa", "atk"), "Mild": ("spa", "def"), "Quiet": ("spa", "spe"),
    "Rash": ("spa", "spd"), "Calm": ("spd", "atk"), "Gentle": ("spd", "def"),
    "Sassy": ("spd", "spe"), "Careful": ("spd", "spa"),
}


@lru_cache(maxsize=1)
def _data() -> dict:
    path = resource_path("assets", "data", "champions.json")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"species": []}


@lru_cache(maxsize=1)
def _by_name() -> dict[str, dict]:
    index: dict[str, dict] = {}
    for sp in _data().get("species", []):
        index[sp["name"].lower()] = sp
        index[sp["id"].lower()] = sp
    return index


def is_loaded() -> bool:
    return bool(_data().get("species"))


def all_species() -> list[dict]:
    """All legal species, ordered by national dex number."""
    return sorted(_data().get("species", []), key=lambda s: s.get("num", 0))


def search(query: str) -> list[dict]:
    q = query.strip().lower()
    species = all_species()
    if not q:
        return species
    return [s for s in species if q in s["name"].lower()]


def get_species(name: str) -> dict | None:
    return _by_name().get(name.strip().lower())


def calc_stat(stat: str, base: int, iv: int, ev: int, level: int, nature: str) -> int:
    """Compute a real stat value (gen 3+ formula)."""
    level = level or 50
    common = math.floor((2 * base + iv + ev // 4) * level / 100)
    if stat == "hp":
        if base == 1:  # Shedinja-style
            return 1
        return common + level + 10
    plus, minus = NATURES.get(nature, (None, None))
    mod = 1.1 if stat == plus else 0.9 if stat == minus else 1.0
    return math.floor((common + 5) * mod)


def calc_all_stats(
    base_stats: dict[str, int],
    ivs: dict[str, int],
    evs: dict[str, int],
    level: int,
    nature: str,
) -> dict[str, int]:
    return {
        s: calc_stat(s, base_stats.get(s, 0), ivs.get(STAT_LABELS[s], 31),
                     evs.get(STAT_LABELS[s], 0), level, nature)
        for s in STAT_KEYS
    }


def calc_stat_sp(stat: str, base: int, sp: int, level: int, nature: str) -> int:
    """
    Compute a stat the Champions way: perfect IVs, SP added linearly.
    Equivalent to the standard formula with IV=31 and EV=sp*8 at Lv50.
    """
    level = level or CHAMPIONS_LEVEL
    common = math.floor((2 * base + PERFECT_IV) * level / 100)
    if stat == "hp":
        if base == 1:
            return 1
        return common + level + 10 + sp
    plus, minus = NATURES.get(nature, (None, None))
    mod = 1.1 if stat == plus else 0.9 if stat == minus else 1.0
    return math.floor((common + 5 + sp) * mod)


def calc_all_stats_sp(
    base_stats: dict[str, int],
    sp: dict[str, int],
    level: int,
    nature: str,
) -> dict[str, int]:
    """sp keyed by STAT_ORDER labels (HP/Atk/…). Returns dict keyed by STAT_KEYS."""
    return {
        s: calc_stat_sp(s, base_stats.get(s, 0), sp.get(STAT_LABELS[s], 0), level, nature)
        for s in STAT_KEYS
    }


def sprite_path(species_id: str):
    """Filesystem path to a bundled sprite (may not exist)."""
    return resource_path("assets", "sprites", f"{species_id}.png")


# ----------------------------------------------------------------------
# Move / ability metadata + descriptions
# ----------------------------------------------------------------------

@lru_cache(maxsize=1)
def _moves() -> dict[str, dict]:
    try:
        data = json.loads(
            resource_path("assets", "data", "moves.json").read_text(encoding="utf-8")
        )
        return {m["name"].lower(): m for m in data.get("moves", [])}
    except (OSError, json.JSONDecodeError):
        return {}


@lru_cache(maxsize=1)
def _abilities() -> dict[str, dict]:
    try:
        data = json.loads(
            resource_path("assets", "data", "abilities.json").read_text(encoding="utf-8")
        )
        return {a["name"].lower(): a for a in data.get("abilities", [])}
    except (OSError, json.JSONDecodeError):
        return {}


def get_move(name: str) -> dict | None:
    return _moves().get(name.strip().lower()) if name else None


def get_ability(name: str) -> dict | None:
    return _abilities().get(name.strip().lower()) if name else None


def ability_desc(name: str) -> str:
    a = get_ability(name)
    return a["desc"] if a else ""


def move_summary(name: str) -> str:
    """Compact one-line move summary, e.g. 'Fire · Special · 90 BP · 100% · Pri +1'."""
    m = get_move(name)
    if not m:
        return ""
    bits = [m["type"], m["category"]]
    if m.get("power"):
        bits.append(f"{m['power']} BP")
    acc = m.get("accuracy", "—")
    bits.append(f"{acc}%" if isinstance(acc, int) else "—")
    pri = m.get("priority", 0)
    if pri:
        bits.append(f"Pri {pri:+d}")
    return "  ·  ".join(b for b in bits if b)


def type_icon_path(type_name: str):
    """Path to a bundled type icon (may not exist)."""
    return resource_path("assets", "types", f"{type_name.strip().lower()}.gif")


def category_icon_path(category: str):
    """Path to a Physical/Special/Status icon (may not exist)."""
    return resource_path("assets", "categories", f"{category.strip().lower()}.png")


def move_tooltip(name: str) -> str:
    m = get_move(name)
    if not m:
        return ""
    return f"{move_summary(name)}\nPP {m.get('pp', 0)}\n{m.get('desc', '')}"
